---
- name: Install required packages for Docker CE
  yum:
    name: "{{ item }}"
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  become: yes

- name: Set up the Docker CE repository
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  become: yes

- name: Install Docker CE
  yum:
    name: "{{ item }}"
  with_items:
    - docker-ce-18.04.0-ce
  become: yes

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
